global:
  environment: main
  chart:
    # -- Github repositroy it resides in
    repo: https://github.com/Oran901/js_project.git
    # -- Branch/Commit/Tag that we are looking at
    targetRevision: HEAD
    # -- Points towards the values file used by the environment
fruit:
  tag: "90bf5ed37dfa5946387623d7dda988f3f0ee1a79"
