global:
  environment: main
  chart:
    # -- Github repositroy it resides in
    repo: https://github.com/Oran901/js_project.git
    # -- Branch/Commit/Tag that we are looking at
    targetRevision: HEAD
    # -- Points towards the values file used by the environment
fruit:
  tag: "54f50c4098cb62935b735460a42251e4e9ed8435"
