global:
  environment: dev
  chart:
    # -- Github repositroy it resides in
    repo: https://github.com/Oran901/js_project.git
    # -- Branch/Commit/Tag that we are looking at
    targetRevision: HEAD 
  # -- Points towards the values file used by the environment

front:
  tag: "latest"

back:
  tag: "latest"