version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongodb/init.js:/docker-entrypoint-initdb.d/init.js
  
  fruit:
    build:
      context: ./src
    image: fruit
    container_name: fruit-container
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      DB_PASSWORD: "password"
      DB_USERNAME: "root"
      DB_HOST: "mongo-container"
    ports:
      - "80:3000"
    depends_on:
      - mongo  

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30  
      - WATCHTOWER_CLEANUP=true       
      - WATCHTOWER_LABEL_ENABLE=true  

volumes:
  mongo-data: