apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.fruit.image }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.{{ .Values.ingress.domain }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.fruit.image }}-svc  
                port:
                  number: {{ .Values.fruit.port }}  