apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.environment }}-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.db }}
  dataFrom:
  - extract:
      key: "atlas_secret"