apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.fruit.image }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Values.fruit.image }}
  ports:
    - port: {{ .Values.fruit.port }}
      targetPort: {{ .Values.fruit.port }}
