version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongodb/init.js:/docker-entrypoint-initdb.d/init.js
  
  fruit:
    build:
      context: ./src
    image: fruit
    container_name: fruit-container
    environment:
      DB_PASSWORD: "password"
      DB_USERNAME: "root"
      DB_HOST: "mongo-container"
    ports:
      - "80:3000"
    depends_on:
      - mongo  

volumes:
  mongo-data:
