name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "app/**"
  workflow_dispatch:

env:                 
  DOCKER_REPOSITORY: fruit
  DOCKER_REGISTRY: oran901
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
      continue-on-error: false
    
    
    - name: Docker-compose build and test
      id: docker-compose-up
      run: |
        # runs docker-compose and npm tests
        docker-compose -f app/docker-compose.yaml up -d
        sleep 5
        docker exec fruit-container npm test

              
    
    - name: Build, tag, and push image to docker hub
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to docker hub so that it can
        # be deployed to EKS.
        pwd
        docker tag oran901/fruit:latest $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG 
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
        echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  update-values:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install yq
        run: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
            sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in values.yaml
        run: |
            yq e '.main.tag = "${{ github.sha }}"' -i git-ops/environments/main/values.yaml

      - name: Check changes
        run: cat git-ops/environments/main/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "Oran901"
          git config user.email "${{ secrets.EMAIL }}"  
          git add .
          git commit -m "Update backend image to ${{ github.sha }}"
          git push origin main