name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "app/**"
  workflow_dispatch:

env:                 
  DOCKER_REPOSITORY: fruit
  DOCKER_REGISTRY: oran901
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
              
    
    - name: Build, tag, and push image to docker hub
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to docker hub so that it can
        # be deployed to EKS.
        pwd
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
        echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
