name: Update Values on PR to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed  

jobs:
  update-values:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in values.yaml
        run: |
          yq e '.main.tag = "${{ github.sha }}"' -i git-ops/environments/main/values.yaml

      - name: Check changes
        run: cat git-ops/environments/main/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "Oran901"
          git config user.email "${{ secrets.EMAIL }}"  
          git add .
          git commit -m "Update backend image to ${{ github.sha }}"
          git push origin main