name: Update Values on PR to Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed  

env:                 
  DOCKER_REPOSITORY: fruit
  DOCKER_REGISTRY: oran901

jobs:
  update-values:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}


      - name: Build, tag, and push image to docker hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to docker hub so that it can
          # be deployed to EKS.
          pwd
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG ./app/src 
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in values.yaml
        run: |
          yq e '.fruit.tag = "${{ github.sha }}"' -i git-ops/environments/main/values.yaml

      - name: Check changes
        run: cat git-ops/environments/main/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "Oran901"
          git config user.email "${{ secrets.EMAIL }}"  
          git add .
          git commit -m "Update backend image to ${{ github.sha }}"
          git push origin main